[package]
name = "auto_commit"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simple_config_parser = "0.1.6"
chrono = { version = "0.4", features = ["unstable-locales"] }
rand = "0.8"