name: Commit History
on:
  workflow_dispatch:
jobs:
  Commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.head_ref }}
      - name: run
        working-directory: ./auto_commit
        run: |
          cargo run -- --token ${{ secrets.GITHUB_TOKEN }} --repo ${{ github.repository }}
